/* eslint-disable react/destructuring-assignment */
import React, { FC } from 'react';

import Head from 'next/head';
import NicoNicoThumbnail from '../../src/components/nicoNicoThumbnail';
import styles from '../../styles/Home.module.css';
import { store } from '../../src/utils/firebase';
import db from '../../src/utils/firebase-admin';

const MovieList: FC = (data: any) => {
  const { movies } = data;

  const addMoview = () => {
    store.collection('movies').add({
      id: 'xxx',
      title: 'yyyy',
    })
      .then(() => {
        alert('登録されました');
      })
      .catch((err) => {
        console.log(err);
        alert('登録できませんでした');
      });
  };

  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Next App Sample 0801</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.grid}>
          {movies.map((item: any) => (
            <NicoNicoThumbnail
              title={item.title}
              movieId={item.movieId}
            />
          ))}
        </main>
      </div>
    </>
  );
};

export async function getServerSideProps(context: any) {
  const { category } = context.query;

  const movies = [] as any;
  const list = await db.collection('movies')
    .where('category', '==', category)
    .get();

  list.docs.forEach((doc: any) => {
    movies.push(doc.data());
  });

  return { props: { movies } };
}

export default MovieList;
