import React, { FC, useEffect } from 'react';

import Head from 'next/head';
import LinkComponent from '../src/components/linkComponent';
import styles from '../styles/Home.module.css';
import { store } from '../src/utils/firebase';
import db from '../src/utils/firebase-admin';

const List: FC = () => {
  const movieList = [
    {
      title: 'ボカロ実況動画',
      category: 'vocaloid',
    },
    {
      title: '実況動画',
      category: 'commentary',
    },
    {
      title: 'RTA動画',
      category: 'rta',
    },
    {
      title: 'TAS動画',
      category: 'tas',
    },
  ];

  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Next App Sample 0801</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <div className={styles.grid}>
            {movieList.map((item) => (
              <LinkComponent
                url={`/myList/${item.category}`}
                title={item.title}
              />
            ))}
          </div>
        </main>
      </div>
    </>
  );
};

export async function getServerSideProps() {
  const movies = [] as any;
  const ref = await db.collection('movies').get();

  ref.docs.forEach((doc: any) => {
    const data = { id: doc.id };
    movies.push(data);
  });

  return { props: { movies } };
}

export default List;
